
#ifndef LIBDABBARPC_RPC_H
#define	LIBDABBARPC_RPC_H

#include <paths.h>
#include <google/protobuf-c/protobuf-c-rpc.h>
#include <libdabba-rpc/dabba.pb-c.h>

#ifndef DABBA_RPC_DEFAULT_HOST_NAME
#define DABBA_RPC_DEFAULT_HOST_NAME "localhost"
#endif				/* DABBA_RPC_DEFAULT_HOST_NAME */

/* 0xDABA = 55994 */
#ifndef DABBA_RPC_DEFAULT_PORT
#define DABBA_RPC_DEFAULT_PORT "55994"
#endif				/* DABBA_RPC_DEFAULT_PORT */

#ifndef DABBA_RPC_DEFAULT_TCP_SERVER_NAME
#define DABBA_RPC_DEFAULT_TCP_SERVER_NAME DABBA_RPC_DEFAULT_HOST_NAME":"DABBA_RPC_DEFAULT_PORT
#endif				/* DABBA_RPC_DEFAULT_TCP_SERVER_NAME */

#ifndef DABBA_RPC_DEFAULT_LOCAL_SERVER_NAME
#define DABBA_RPC_DEFAULT_LOCAL_SERVER_NAME _PATH_VARRUN "dabba/dabba"
#endif				/* DABBA_RPC_DEFAULT_LOCAL_SERVER_NAME */

#endif				/* LIBDABBARPC_RPC_H */
